### ISSUE TITLE
Assumes a vault called "my"

### ISSUE THREAD

**Issue by stooj** [apetresc/rofi-1pass#3]
Thanks so much for this script! I've hit a bit of a snag though; the script fails when there is no account called `my`.

Perhaps I didn't set up 1password correctly, but I don't have an account called `my`, so have had to change the signin line.

**Comment by khanyong** [comment]
You should carefully read this article 
[https://support.1password.com/command-line-getting-started/]

after `op signing example.1password.com *****` ,  your subdomain will be changed "my". Because my.1password.com is common domain for user.

**Comment by stooj** [comment]
Ah, thank you for the heads up. My mistake.
