### ISSUE TITLE
Only handles passwords from templateUuid: 001

### ISSUE THREAD

**Issue by chrishoage** [apetresc/rofi-1pass#4]
The Login template (`templateUuid: "001"`) places the password in `detials.fields[].designation = 'password`

The Password template (`templateUuid: "005"`) places the password in `details.password`

`>> Copy Password` only handles a Login template, not a Password template, and returns `jq: error (at <stdin>:1): Cannot iterate over null (null)` since there is no matching field. 

Perhaps `op get item` should read the `templateUuid` and pick the appropriate path based on the response?

**Comment by apetresc** [comment]
Good point – should be an easy fix.

I've migrated to using bitwarden myself, so it might take me a little while to get around to setting up a test environment for this. If anyone else wants to take this up, it should be straightforward.

**Comment by chrishoage** [comment]
I'm going though my old open issues and cleaning it up. Since 1Password has an electron application which supports linux this can now be closed.
